/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ../../public/models/fox.glb -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube005: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Circle: THREE.Mesh;
    Plane002: THREE.Mesh;
    Icosphere: THREE.Mesh;
    Circle001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Sphere: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Sphere010: THREE.Mesh;
    Sphere011: THREE.Mesh;
  };
  materials: {
    ["body.003"]: THREE.MeshStandardMaterial;
    body: THREE.MeshStandardMaterial;
    ["body.002"]: THREE.MeshStandardMaterial;
    eye: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["eye fur"]: THREE.MeshStandardMaterial;
    cheek: THREE.MeshStandardMaterial;
    cup: THREE.MeshPhysicalMaterial;
    ["cup.001"]: THREE.MeshStandardMaterial;
    ["cup.003"]: THREE.MeshStandardMaterial;
    ["body.001"]: THREE.MeshStandardMaterial;
    boba: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/fox.glb") as GLTFResult;
  const gltf = useLoader(GLTFLoader, "/models/fox.glb");
  return <primitive object={gltf.scene} />;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials["body.003"]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.body} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.body} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.body} />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["body.002"]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.eye}
        position={[0.113, 1.074, 0.312]}
        rotation={[0.159, 0.015, 0.092]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.eye}
        position={[0.002, 0.978, 0.42]}
        rotation={[1.505, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[-0.002, 0.707, 0.388]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["eye fur"]}
        position={[0.129, 1.206, 0.272]}
        rotation={[1.469, 0.576, -0.449]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.cheek}
        position={[0.189, 1.044, 0.33]}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials["eye fur"]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials.cup}
        position={[0.008, 0.641, 0.369]}
      />
      <group position={[-0.005, 0.311, 0.371]} scale={[0.202, 0.308, 0.202]}>
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["cup.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["cup.003"]}
        />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials.body} />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials["eye fur"]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["body.001"]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.cheek}
        position={[0.4, 0.363, 0.529]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.boba}
        position={[-0.077, 0.047, 0.333]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.boba}
        position={[-0.017, 0.047, 0.308]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.boba}
        position={[0.001, 0.047, 0.276]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials.boba}
        position={[0.065, 0.047, 0.355]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials.boba}
        position={[0.063, 0.047, 0.435]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials.boba}
        position={[-0.057, 0.047, 0.437]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials.boba}
        position={[0.001, 0.047, 0.445]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={materials.boba}
        position={[0.053, 0.124, 0.395]}
        scale={0.035}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials.boba}
        position={[-0.031, 0.115, 0.352]}
        scale={0.035}
      />
    </group>
  );
}

useGLTF.preload("/models/fox.glb");
