/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ../../public/models/ISS_stationary.glb -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder022_7: THREE.Mesh;
    Cylinder022_8: THREE.Mesh;
    Cylinder022_9: THREE.Mesh;
    Cylinder022_10: THREE.Mesh;
    Cylinder022_11: THREE.Mesh;
    Cylinder022_12: THREE.Mesh;
    Cylinder022_13: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere002_1: THREE.Mesh;
    Sphere002_2: THREE.Mesh;
    Sphere002_3: THREE.Mesh;
    sm_ext_sm000: THREE.Mesh;
    sm_ext_sm000_1: THREE.Mesh;
    sm_ext_sm000_2: THREE.Mesh;
    sm_ext_sm000_3: THREE.Mesh;
    sm_ext_sm000_4: THREE.Mesh;
    Sphere002_8: THREE.Mesh;
    Sphere002_9: THREE.Mesh;
    Sphere002_10: THREE.Mesh;
    Sphere002_11: THREE.Mesh;
    Sphere002_12: THREE.Mesh;
    Sphere002_13: THREE.Mesh;
    Sphere002_14: THREE.Mesh;
    Sphere002_15: THREE.Mesh;
    sm_ext_sm000_5: THREE.Mesh;
    sm_ext_sm000_6: THREE.Mesh;
    sm_ext_sm000_7: THREE.Mesh;
    sm_ext_sm000_8: THREE.Mesh;
    sm_ext_sm000_9: THREE.Mesh;
    sm_ext_sm000_10: THREE.Mesh;
    sm_ext_sm000_11: THREE.Mesh;
    sm_ext_sm000_12: THREE.Mesh;
    sm_ext_sm000_13: THREE.Mesh;
    sm_ext_sm000_14: THREE.Mesh;
    sm_ext_sm000_15: THREE.Mesh;
    sm_ext_sm000_16: THREE.Mesh;
    sm_ext_sm000_17: THREE.Mesh;
    sm_ext_sm000_18: THREE.Mesh;
    sm_ext_sm000_19: THREE.Mesh;
    sm_ext_sm000_20: THREE.Mesh;
    sm_ext_sm000_21: THREE.Mesh;
    sm_ext_sm000_22: THREE.Mesh;
    sm_ext_sm000_23: THREE.Mesh;
    sm_ext_sm000_24: THREE.Mesh;
    sm_ext_sm000_25: THREE.Mesh;
    sm_ext_sm000_26: THREE.Mesh;
    sm_ext_sm000_27: THREE.Mesh;
    sm_ext_sm000_28: THREE.Mesh;
    sm_ext_sm000_29: THREE.Mesh;
    sm_ext_sm000_30: THREE.Mesh;
    sm_ext_sm000_31: THREE.Mesh;
    sm_ext_sm000_32: THREE.Mesh;
    sm_ext_sm000_33: THREE.Mesh;
    sm_ext_sm000_34: THREE.Mesh;
    sm_ext_sm000_35: THREE.Mesh;
    sm_ext_sm000_36: THREE.Mesh;
    sm_ext_sm000_37: THREE.Mesh;
    sm_ext_sm000_38: THREE.Mesh;
    sm_ext_sm000_39: THREE.Mesh;
    sm_ext_sm000_40: THREE.Mesh;
    sm_ext_sm000_41: THREE.Mesh;
    sm_ext_sm000_42: THREE.Mesh;
    sm_ext_sm000_43: THREE.Mesh;
    sm_ext_sm000_44: THREE.Mesh;
    sm_ext_sm000_45: THREE.Mesh;
    sm_ext_sm000_46: THREE.Mesh;
    sm_ext_sm000_47: THREE.Mesh;
    sm_ext_sm000_48: THREE.Mesh;
    sm_ext_sm000_49: THREE.Mesh;
    sm_ext_sm000_50: THREE.Mesh;
    sm_ext_sm000_51: THREE.Mesh;
    sm_ext_sm000_52: THREE.Mesh;
    sm_ext_sm000_53: THREE.Mesh;
    sm_ext_sm000_54: THREE.Mesh;
    sm_ext_sm000_55: THREE.Mesh;
    sm_ext_sm000_56: THREE.Mesh;
    sm_ext_sm000_57: THREE.Mesh;
    sm_ext_sm000_58: THREE.Mesh;
    panel_bracket_p: THREE.Mesh;
    panel_bracket_s: THREE.Mesh;
    Sphere002_4: THREE.Mesh;
    Sphere002_5: THREE.Mesh;
    Sphere002_6: THREE.Mesh;
    Sphere002_7: THREE.Mesh;
    z1_ext_01001: THREE.Mesh;
    z1_ext_01001_1: THREE.Mesh;
    z1_ext_01001_2: THREE.Mesh;
    z1_ext_01001_3: THREE.Mesh;
    z1_ext_01001_4: THREE.Mesh;
    Cylinder022_14: THREE.Mesh;
    Cylinder022_15: THREE.Mesh;
    Cylinder022_16: THREE.Mesh;
    Cylinder022_17: THREE.Mesh;
    Cylinder022_18: THREE.Mesh;
    Cylinder022_19: THREE.Mesh;
    z1_ext_01001_5: THREE.Mesh;
    z1_ext_01001_6: THREE.Mesh;
    s0_ani000: THREE.Mesh;
    s0_ani000_1: THREE.Mesh;
    s0_ani000_2: THREE.Mesh;
    s0_ani000_3: THREE.Mesh;
    s0_ani000_4: THREE.Mesh;
    mss_mbs001: THREE.Mesh;
    mss_mbs001_1: THREE.Mesh;
    mss_mbs001_2: THREE.Mesh;
    mss_mbs001_3: THREE.Mesh;
    ["11_Canadarm2"]: THREE.Mesh;
    ["11_Canadarm2_02"]: THREE.Mesh;
    ["11_Canadarm2_03"]: THREE.Mesh;
    ["11_Canadarm2_04"]: THREE.Mesh;
    ["11_Canadarm2_05"]: THREE.Mesh;
    ["11_Canadarm2_06"]: THREE.Mesh;
    ["11_Canadarm2_07"]: THREE.Mesh;
    ["11_Canadarm2_08"]: THREE.Mesh;
    Cylinder022_83: THREE.Mesh;
    Cylinder022_84: THREE.Mesh;
    ["29_DEXTRE001"]: THREE.Mesh;
    ["29_DEXTRE002"]: THREE.Mesh;
    ["29_DEXTRE003"]: THREE.Mesh;
    ["29_DEXTRE004"]: THREE.Mesh;
    ["29_DEXTRE005"]: THREE.Mesh;
    ["29_DEXTRE006"]: THREE.Mesh;
    ["29_DEXTRE007"]: THREE.Mesh;
    ["29_DEXTRE008"]: THREE.Mesh;
    ["29_DEXTRE009"]: THREE.Mesh;
    ["29_DEXTRE010"]: THREE.Mesh;
    ["29_DEXTRE011"]: THREE.Mesh;
    ["29_DEXTRE012"]: THREE.Mesh;
    ["29_DEXTRE013"]: THREE.Mesh;
    ["29_DEXTRE014"]: THREE.Mesh;
    ["29_DEXTRE015"]: THREE.Mesh;
    s0_ani000_5: THREE.Mesh;
    s0_ani000_6: THREE.Mesh;
    s0_ani000_7: THREE.Mesh;
    s0_ani000_8: THREE.Mesh;
    s0_ani000_9: THREE.Mesh;
    s0_ani000_15: THREE.Mesh;
    s0_ani000_16: THREE.Mesh;
    s0_ani000_17: THREE.Mesh;
    s0_ani000_18: THREE.Mesh;
    s0_ani000_19: THREE.Mesh;
    s0_ani000_20: THREE.Mesh;
    s0_ani000_21: THREE.Mesh;
    p6_ani000: THREE.Mesh;
    p6_ani000_1: THREE.Mesh;
    p6_ani000_2: THREE.Mesh;
    p6_ani000_3: THREE.Mesh;
    p6_ani000_4: THREE.Mesh;
    Cube008_46: THREE.Mesh;
    Cube008_47: THREE.Mesh;
    Cube008_48: THREE.Mesh;
    Cube008_49: THREE.Mesh;
    p6_ani000_10: THREE.Mesh;
    p6_ani000_11: THREE.Mesh;
    p6_ani000_12: THREE.Mesh;
    p6_ani000_13: THREE.Mesh;
    p6_ani000_14: THREE.Mesh;
    p6_ani000_15: THREE.Mesh;
    p6_ani000_16: THREE.Mesh;
    p6_ani000_17: THREE.Mesh;
    p6_ani000_18: THREE.Mesh;
    p6_ani000_19: THREE.Mesh;
    p6_ani000_30: THREE.Mesh;
    p6_ani000_31: THREE.Mesh;
    p6_ani000_32: THREE.Mesh;
    p6_ani000_33: THREE.Mesh;
    p6_ani000_34: THREE.Mesh;
    p6_ani000_35: THREE.Mesh;
    ESP3000: THREE.Mesh;
    ESP3000_1: THREE.Mesh;
    ESP3000_2: THREE.Mesh;
    ESP3000_3: THREE.Mesh;
    ESP3000_4: THREE.Mesh;
    esp2_lo000_4: THREE.Mesh;
    esp2_lo000_5: THREE.Mesh;
    esp2_lo000_6: THREE.Mesh;
    esp2_lo000_7: THREE.Mesh;
    esp2_lo000_8: THREE.Mesh;
    esp2_lo000_9: THREE.Mesh;
    esp2_lo000_10: THREE.Mesh;
    AMS2000: THREE.Mesh;
    AMS2000_1: THREE.Mesh;
    AMS2000_2: THREE.Mesh;
    Cylinder022_63: THREE.Mesh;
    Cylinder022_64: THREE.Mesh;
    Cylinder022_65: THREE.Mesh;
    s0_ani000_10: THREE.Mesh;
    s0_ani000_11: THREE.Mesh;
    s0_ani000_12: THREE.Mesh;
    s0_ani000_13: THREE.Mesh;
    s0_ani000_14: THREE.Mesh;
    s0_ani000_22: THREE.Mesh;
    s0_ani000_23: THREE.Mesh;
    s0_ani000_24: THREE.Mesh;
    s0_ani000_25: THREE.Mesh;
    s0_ani000_26: THREE.Mesh;
    s0_ani000_27: THREE.Mesh;
    s0_ani000_28: THREE.Mesh;
    p6_ani000_5: THREE.Mesh;
    p6_ani000_6: THREE.Mesh;
    p6_ani000_7: THREE.Mesh;
    p6_ani000_8: THREE.Mesh;
    p6_ani000_9: THREE.Mesh;
    Cube008_50: THREE.Mesh;
    Cube008_51: THREE.Mesh;
    Cube008_52: THREE.Mesh;
    Cube008_53: THREE.Mesh;
    p6_ani000_20: THREE.Mesh;
    p6_ani000_21: THREE.Mesh;
    p6_ani000_22: THREE.Mesh;
    p6_ani000_23: THREE.Mesh;
    p6_ani000_36: THREE.Mesh;
    p6_ani000_37: THREE.Mesh;
    p6_ani000_38: THREE.Mesh;
    p6_ani000_39: THREE.Mesh;
    p6_ani000_40: THREE.Mesh;
    p6_ani000_41: THREE.Mesh;
    p6_ani000_24: THREE.Mesh;
    p6_ani000_25: THREE.Mesh;
    p6_ani000_26: THREE.Mesh;
    p6_ani000_27: THREE.Mesh;
    p6_ani000_28: THREE.Mesh;
    p6_ani000_29: THREE.Mesh;
    esp2_lo000_11: THREE.Mesh;
    esp2_lo000_12: THREE.Mesh;
    esp2_lo000_13: THREE.Mesh;
    esp2_lo000_14: THREE.Mesh;
    esp2_lo000_15: THREE.Mesh;
    esp2_lo000_16: THREE.Mesh;
    esp2_lo000_17: THREE.Mesh;
    esp2_lo000_18: THREE.Mesh;
    Cylinder022_36: THREE.Mesh;
    Cylinder022_37: THREE.Mesh;
    Cylinder022_38: THREE.Mesh;
    Cylinder022_39: THREE.Mesh;
    Cylinder022_46: THREE.Mesh;
    Cylinder022_47: THREE.Mesh;
    Cylinder022_48: THREE.Mesh;
    Cylinder022_49: THREE.Mesh;
    Cylinder022_50: THREE.Mesh;
    Cylinder022_51: THREE.Mesh;
    Cylinder022_52: THREE.Mesh;
    Cylinder022_53: THREE.Mesh;
    Cylinder022_54: THREE.Mesh;
    Cube008_35: THREE.Mesh;
    Cube008_36: THREE.Mesh;
    Cube008_37: THREE.Mesh;
    Cube008_38: THREE.Mesh;
    RapidScat_dish: THREE.Mesh;
    Cylinder022_55: THREE.Mesh;
    Cylinder022_56: THREE.Mesh;
    Cylinder022_57: THREE.Mesh;
    Cylinder022_58: THREE.Mesh;
    Cylinder022_59: THREE.Mesh;
    Cylinder022_60: THREE.Mesh;
    Cylinder022_66: THREE.Mesh;
    Cylinder022_67: THREE.Mesh;
    Cylinder022_68: THREE.Mesh;
    Cylinder022_69: THREE.Mesh;
    Cylinder022_70: THREE.Mesh;
    Cylinder022_71: THREE.Mesh;
    ["31_Robotic_Arm"]: THREE.Mesh;
    ["31_Robotic_Arm001"]: THREE.Mesh;
    ["31_Robotic_Arm002"]: THREE.Mesh;
    ["31_Robotic_Arm003"]: THREE.Mesh;
    ["31_Robotic_Arm004"]: THREE.Mesh;
    ["31_Robotic_Arm005"]: THREE.Mesh;
    Cube008_39: THREE.Mesh;
    Cube008_40: THREE.Mesh;
    Cube008_41: THREE.Mesh;
    Cube008_42: THREE.Mesh;
    Cube008_43: THREE.Mesh;
    Cube008_44: THREE.Mesh;
    Destiny_Window_Cover: THREE.Mesh;
    Cylinder022_20: THREE.Mesh;
    Cylinder022_21: THREE.Mesh;
    Cylinder022_22: THREE.Mesh;
    Cylinder022_23: THREE.Mesh;
    Cylinder022_24: THREE.Mesh;
    Cylinder022_25: THREE.Mesh;
    Cylinder022_26: THREE.Mesh;
    esp2_lo000: THREE.Mesh;
    esp2_lo000_1: THREE.Mesh;
    esp2_lo000_2: THREE.Mesh;
    esp2_lo000_3: THREE.Mesh;
    Cylinder022_27: THREE.Mesh;
    Cylinder022_28: THREE.Mesh;
    Cylinder022_29: THREE.Mesh;
    Cylinder022_30: THREE.Mesh;
    Cylinder022_40: THREE.Mesh;
    Cylinder022_41: THREE.Mesh;
    Cylinder022_42: THREE.Mesh;
    Cylinder022_43: THREE.Mesh;
    Cylinder022_44: THREE.Mesh;
    Cylinder022_45: THREE.Mesh;
    ["38_Cupola001"]: THREE.Mesh;
    ["38_Cupola002"]: THREE.Mesh;
    ["38_Cupola003"]: THREE.Mesh;
    ["38_Cupola004"]: THREE.Mesh;
    ["38_Cupola005"]: THREE.Mesh;
    ["38_Cupola006"]: THREE.Mesh;
    ["38_Cupola007"]: THREE.Mesh;
    ISS: THREE.Mesh;
    Cylinder022_31: THREE.Mesh;
    Cylinder022_32: THREE.Mesh;
    Cylinder022_33: THREE.Mesh;
    Cylinder022_34: THREE.Mesh;
    Cylinder022_35: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    hinge_02_p: THREE.Mesh;
    Cube008_3: THREE.Mesh;
    Cube008_4: THREE.Mesh;
    hinge_04_p: THREE.Mesh;
    hinge_01_p: THREE.Mesh;
    Cube008_7: THREE.Mesh;
    Cube008_8: THREE.Mesh;
    hinge_03_p: THREE.Mesh;
    Cube008_10: THREE.Mesh;
    Cube008_11: THREE.Mesh;
    Cube008_12: THREE.Mesh;
    Cube008_13: THREE.Mesh;
    hinge_02_s: THREE.Mesh;
    Cube008_15: THREE.Mesh;
    Cube008_16: THREE.Mesh;
    hinge_04_s: THREE.Mesh;
    hinge_03_s: THREE.Mesh;
    Cube008_19: THREE.Mesh;
    Cube008_20: THREE.Mesh;
    Cube008_21: THREE.Mesh;
    Cube008_22: THREE.Mesh;
    hinge_01_s: THREE.Mesh;
    Cube008_24: THREE.Mesh;
    Cube008_25: THREE.Mesh;
    Cube008_26: THREE.Mesh;
    Cube008_27: THREE.Mesh;
    Cylinder022: THREE.Mesh;
    Cylinder022_1: THREE.Mesh;
    Cylinder022_2: THREE.Mesh;
    Cylinder022_3: THREE.Mesh;
    Cylinder022_4: THREE.Mesh;
    Cylinder022_5: THREE.Mesh;
    Cylinder022_6: THREE.Mesh;
  };
  materials: {
    ISS_01_dull: THREE.MeshStandardMaterial;
    ISS_01_shiny_n: THREE.MeshStandardMaterial;
    ISS_AO_01: THREE.MeshStandardMaterial;
    ISS_AO_02: THREE.MeshStandardMaterial;
    ISS_02_dull: THREE.MeshStandardMaterial;
    ISS_03_dull: THREE.MeshStandardMaterial;
    ISS_AO_06: THREE.MeshStandardMaterial;
    shiny_panel: THREE.MeshStandardMaterial;
    ["olive *"]: THREE.MeshStandardMaterial;
    ISS_AO_04: THREE.MeshStandardMaterial;
    ISS_AO_03: THREE.MeshStandardMaterial;
    ["ISS_01_dark *"]: THREE.MeshStandardMaterial;
    foil_silver: THREE.MeshStandardMaterial;
    ISS_03_shiny_n: THREE.MeshStandardMaterial;
    ["ISS_02_dark *"]: THREE.MeshStandardMaterial;
    ISS_04_dull: THREE.MeshStandardMaterial;
    ISS_AO_05: THREE.MeshStandardMaterial;
    ISS_AO_07: THREE.MeshStandardMaterial;
    ISS_AO_08: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    base_metal: THREE.MeshStandardMaterial;
    ["ISS_03_dull.001"]: THREE.MeshStandardMaterial;
    ecostress: THREE.MeshStandardMaterial;
    ["plastic black"]: THREE.MeshStandardMaterial;
    ecostressWhite: THREE.MeshStandardMaterial;
    ["ISS_03_dull.002"]: THREE.MeshStandardMaterial;
    ["ecostress metal"]: THREE.MeshStandardMaterial;
    ecostress_dexter: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/ISS_stationary.glb"
  ) as GLTFResult;
  const gltf = useLoader(GLTFLoader, "/models/ISS_stationary.glb");
  return <primitive object={gltf.scene} />;
  return (
    <group {...props} dispose={null}>
      <group position={[1.687, 0.846, -11.087]}>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          geometry={nodes.Cube008_1.geometry}
          material={materials.shiny_panel}
        />
      </group>
      <mesh
        geometry={nodes.hinge_02_p.geometry}
        material={materials.ISS_02_dull}
        position={[2.173, 0.797, -12.508]}
      />
      <group position={[2.937, 0.797, -9.63]}>
        <mesh
          geometry={nodes.Cube008_3.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          geometry={nodes.Cube008_4.geometry}
          material={materials.shiny_panel}
        />
      </group>
      <mesh
        geometry={nodes.hinge_04_p.geometry}
        material={materials.ISS_02_dull}
        position={[3.91, 0.797, -12.498]}
      />
      <mesh
        geometry={nodes.hinge_01_p.geometry}
        material={materials.ISS_02_dull}
        position={[1.687, 0.797, -11.087]}
      />
      <group position={[2.167, 0.797, -9.664]}>
        <mesh
          geometry={nodes.Cube008_7.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          geometry={nodes.Cube008_8.geometry}
          material={materials.shiny_panel}
        />
      </group>
      <mesh
        geometry={nodes.hinge_03_p.geometry}
        material={materials.ISS_02_dull}
        position={[2.928, 0.797, -12.542]}
      />
      <group position={[3.906, 0.797, -9.676]}>
        <mesh
          geometry={nodes.Cube008_10.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          geometry={nodes.Cube008_11.geometry}
          material={materials.shiny_panel}
        />
      </group>
      <group position={[-1.687, 0.846, -11.087]}>
        <mesh
          geometry={nodes.Cube008_12.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          geometry={nodes.Cube008_13.geometry}
          material={materials.shiny_panel}
        />
      </group>
      <mesh
        geometry={nodes.hinge_02_s.geometry}
        material={materials.ISS_02_dull}
        position={[-2.173, 0.797, -12.508]}
      />
      <group position={[-2.937, 0.797, -9.63]}>
        <mesh
          geometry={nodes.Cube008_15.geometry}
          material={materials.shiny_panel}
        />
        <mesh
          geometry={nodes.Cube008_16.geometry}
          material={materials.ISS_02_dull}
        />
      </group>
      <mesh
        geometry={nodes.hinge_04_s.geometry}
        material={materials.ISS_02_dull}
        position={[-3.91, 0.797, -12.498]}
      />
      <mesh
        geometry={nodes.hinge_03_s.geometry}
        material={materials.ISS_02_dull}
        position={[-2.928, 0.797, -12.542]}
      />
      <group position={[-3.906, 0.797, -9.676]}>
        <mesh
          geometry={nodes.Cube008_19.geometry}
          material={materials.shiny_panel}
        />
        <mesh
          geometry={nodes.Cube008_20.geometry}
          material={materials.ISS_02_dull}
        />
      </group>
      <group position={[-2.167, 0.797, -9.664]}>
        <mesh
          geometry={nodes.Cube008_21.geometry}
          material={materials.shiny_panel}
        />
        <mesh
          geometry={nodes.Cube008_22.geometry}
          material={materials.ISS_02_dull}
        />
      </group>
      <mesh
        geometry={nodes.hinge_01_s.geometry}
        material={materials.ISS_02_dull}
        position={[-1.687, 0.797, -11.087]}
      />
      <group position={[15.532, -2.123, 19.897]}>
        <mesh geometry={nodes.Cube008_24.geometry} material={materials.white} />
        <mesh
          geometry={nodes.Cube008_25.geometry}
          material={materials.base_metal}
        />
        <mesh
          geometry={nodes.Cube008_26.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.Cube008_27.geometry}
          material={materials["ISS_03_dull.001"]}
        />
      </group>
      <group position={[18.914, -1.957, 16.107]}>
        <mesh
          geometry={nodes.Cylinder022.geometry}
          material={materials.ecostress}
        />
        <mesh
          geometry={nodes.Cylinder022_1.geometry}
          material={materials["plastic black"]}
        />
        <mesh
          geometry={nodes.Cylinder022_2.geometry}
          material={materials.ecostressWhite}
        />
        <mesh
          geometry={nodes.Cylinder022_3.geometry}
          material={materials["ISS_03_dull.002"]}
        />
        <mesh
          geometry={nodes.Cylinder022_4.geometry}
          material={materials["ecostress metal"]}
        />
        <mesh
          geometry={nodes.Cylinder022_5.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.Cylinder022_6.geometry}
          material={materials.ecostress_dexter}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder022_7.geometry}
        material={nodes.Cylinder022_7.material}
      />
      <mesh
        geometry={nodes.Cylinder022_8.geometry}
        material={materials.ISS_01_dull}
      />
      <mesh
        geometry={nodes.Cylinder022_9.geometry}
        material={materials.ISS_01_shiny_n}
      />
      <mesh
        geometry={nodes.Cylinder022_10.geometry}
        material={materials.ISS_AO_01}
      />
      <group position={[0, 0, -3.383]}>
        <mesh
          geometry={nodes.Cylinder022_11.geometry}
          material={materials.ISS_AO_02}
        />
        <mesh
          geometry={nodes.Cylinder022_12.geometry}
          material={materials.ISS_AO_01}
        />
        <mesh
          geometry={nodes.Cylinder022_13.geometry}
          material={materials.ISS_01_dull}
        />
        <group position={[0, 0.735, -2.457]}>
          <mesh
            geometry={nodes.Sphere002.geometry}
            material={nodes.Sphere002.material}
          />
          <mesh
            geometry={nodes.Sphere002_1.geometry}
            material={materials.ISS_02_dull}
          />
          <mesh
            geometry={nodes.Sphere002_2.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.Sphere002_3.geometry}
            material={materials.ISS_AO_02}
          />
          <group position={[0, 0, -12.965]}>
            <mesh
              geometry={nodes.sm_ext_sm000.geometry}
              material={nodes.sm_ext_sm000.material}
            />
            <mesh
              geometry={nodes.sm_ext_sm000_1.geometry}
              material={materials.ISS_03_dull}
            />
            <mesh
              geometry={nodes.sm_ext_sm000_2.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.sm_ext_sm000_3.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.sm_ext_sm000_4.geometry}
              material={materials.ISS_AO_02}
            />
            <group position={[0, -1.159, -1.157]}>
              <mesh
                geometry={nodes.Sphere002_8.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Sphere002_9.geometry}
                material={materials.ISS_AO_06}
              />
              <mesh
                geometry={nodes.Sphere002_10.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.Sphere002_11.geometry}
                material={materials.ISS_02_dull}
              />
            </group>
            <group position={[0, 1.157, -1.157]}>
              <mesh
                geometry={nodes.Sphere002_12.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Sphere002_13.geometry}
                material={materials.ISS_AO_06}
              />
              <mesh
                geometry={nodes.Sphere002_14.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.Sphere002_15.geometry}
                material={materials.ISS_02_dull}
              />
            </group>
            <group position={[2.227, -0.033, -5.257]}>
              <mesh
                geometry={nodes.sm_ext_sm000_5.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_6.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_7.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-2.227, -0.033, -5.26]}>
              <mesh
                geometry={nodes.sm_ext_sm000_8.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_9.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_10.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[3.511, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_11.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_12.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_13.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-3.511, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_14.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_15.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_16.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[5.032, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_17.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_18.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_19.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-5.032, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_20.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_21.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_22.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[6.556, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_23.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_24.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_25.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-6.556, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_26.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_27.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_28.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[8.066, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_29.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_30.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_31.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-8.066, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_32.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_33.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_34.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[9.585, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_35.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_36.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_37.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-9.585, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_38.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_39.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_40.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[11.162, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_41.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_42.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_43.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-11.162, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_44.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_45.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_46.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[12.743, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_47.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_48.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_49.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-12.743, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_50.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_51.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_52.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[14.328, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_53.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_54.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_55.geometry}
                material={materials["olive *"]}
              />
            </group>
            <group position={[-14.328, -0.031, -5.258]}>
              <mesh
                geometry={nodes.sm_ext_sm000_56.geometry}
                material={materials.shiny_panel}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_57.geometry}
                material={materials.ISS_02_dull}
              />
              <mesh
                geometry={nodes.sm_ext_sm000_58.geometry}
                material={materials["olive *"]}
              />
            </group>
            <mesh
              geometry={nodes.panel_bracket_p.geometry}
              material={materials["olive *"]}
              position={[1.896, -0.033, -5.258]}
            />
            <mesh
              geometry={nodes.panel_bracket_s.geometry}
              material={materials["olive *"]}
              position={[-1.896, -0.033, -5.258]}
            />
          </group>
          <group position={[0, -4.587, -1.154]}>
            <mesh
              geometry={nodes.Sphere002_4.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.Sphere002_5.geometry}
              material={materials.ISS_03_dull}
            />
            <mesh
              geometry={nodes.Sphere002_6.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.Sphere002_7.geometry}
              material={materials.ISS_AO_04}
            />
          </group>
        </group>
      </group>
      <group position={[0, 1.759, 0]}>
        <mesh
          geometry={nodes.z1_ext_01001.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.z1_ext_01001_1.geometry}
          material={materials.ISS_AO_03}
        />
        <mesh
          geometry={nodes.z1_ext_01001_2.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          geometry={nodes.z1_ext_01001_3.geometry}
          material={materials["ISS_01_dark *"]}
        />
        <mesh
          geometry={nodes.z1_ext_01001_4.geometry}
          material={materials.foil_silver}
        />
      </group>
      <group position={[0, 0, 2.221]}>
        <mesh
          geometry={nodes.Cylinder022_14.geometry}
          material={nodes.Cylinder022_14.material}
        />
        <mesh
          geometry={nodes.Cylinder022_15.geometry}
          material={materials.ISS_AO_03}
        />
        <mesh
          geometry={nodes.Cylinder022_16.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.Cylinder022_17.geometry}
          material={materials.ISS_AO_01}
        />
        <mesh
          geometry={nodes.Cylinder022_18.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          geometry={nodes.Cylinder022_19.geometry}
          material={materials.ISS_03_shiny_n}
        />
        <group position={[2.729, -0.477, 2.008]}>
          <mesh
            geometry={nodes.z1_ext_01001_5.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.z1_ext_01001_6.geometry}
            material={materials.ISS_03_dull}
          />
        </group>
        <group position={[0, 5.007, 0.967]}>
          <mesh
            geometry={nodes.s0_ani000.geometry}
            material={materials.ISS_02_dull}
          />
          <mesh
            geometry={nodes.s0_ani000_1.geometry}
            material={materials["ISS_02_dark *"]}
          />
          <mesh
            geometry={nodes.s0_ani000_2.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.s0_ani000_3.geometry}
            material={materials.ISS_AO_04}
          />
          <mesh
            geometry={nodes.s0_ani000_4.geometry}
            material={materials.ISS_04_dull}
          />
          <group position={[-2.865, -0.595, 5.17]}>
            <mesh
              geometry={nodes.mss_mbs001.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.mss_mbs001_1.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.mss_mbs001_2.geometry}
              material={materials.ISS_AO_05}
            />
            <mesh
              geometry={nodes.mss_mbs001_3.geometry}
              material={materials.ISS_03_dull}
            />
            <mesh
              geometry={nodes["11_Canadarm2"].geometry}
              material={materials.ISS_03_dull}
              position={[-1.435, 1.59, 0.198]}
            >
              <mesh
                geometry={nodes["11_Canadarm2_02"].geometry}
                material={materials.ISS_03_dull}
                position={[-0.669, 0.356, 0.98]}
              >
                <mesh
                  geometry={nodes["11_Canadarm2_03"].geometry}
                  material={materials.ISS_03_dull}
                  position={[-0.006, 0.358, 0.23]}
                >
                  <mesh
                    geometry={nodes["11_Canadarm2_04"].geometry}
                    material={materials.ISS_03_dull}
                    position={[0.134, 0.254, 0.314]}
                  >
                    <mesh
                      geometry={nodes["11_Canadarm2_05"].geometry}
                      material={materials.ISS_03_dull}
                      position={[-7.344, 0.004, 0.575]}
                    >
                      <mesh
                        geometry={nodes["11_Canadarm2_06"].geometry}
                        material={materials.ISS_03_dull}
                        position={[0.004, 7.344, 0.575]}
                      >
                        <mesh
                          geometry={nodes["11_Canadarm2_07"].geometry}
                          material={materials.ISS_03_dull}
                          position={[-0.288, 0.002, 0.313]}
                        >
                          <mesh
                            geometry={nodes["11_Canadarm2_08"].geometry}
                            material={materials.ISS_03_dull}
                            position={[-0.313, 0.288, 0.002]}
                          >
                            <group position={[0, 1.203, 0]}>
                              <mesh
                                geometry={nodes.Cylinder022_83.geometry}
                                material={materials.ISS_03_dull}
                              />
                              <mesh
                                geometry={nodes.Cylinder022_84.geometry}
                                material={materials.ISS_01_dull}
                              />
                              <mesh
                                geometry={nodes["29_DEXTRE001"].geometry}
                                material={materials.ISS_03_dull}
                                position={[0, 0.22, 0]}
                              >
                                <mesh
                                  geometry={nodes["29_DEXTRE002"].geometry}
                                  material={materials.ISS_03_dull}
                                  position={[0, 1.962, 0.006]}
                                >
                                  <mesh
                                    geometry={nodes["29_DEXTRE003"].geometry}
                                    material={materials.ISS_03_dull}
                                    position={[0, 0.963, 0]}
                                  />
                                </mesh>
                                <mesh
                                  geometry={nodes["29_DEXTRE004"].geometry}
                                  material={materials.ISS_03_dull}
                                  position={[1.38, 1.425, 0]}
                                >
                                  <mesh
                                    geometry={nodes["29_DEXTRE005"].geometry}
                                    material={materials.ISS_03_dull}
                                    position={[0.375, -0.103, 0.269]}
                                  >
                                    <mesh
                                      geometry={nodes["29_DEXTRE006"].geometry}
                                      material={materials.ISS_03_dull}
                                      position={[0.304, -0.113, 0.143]}
                                    >
                                      <mesh
                                        geometry={
                                          nodes["29_DEXTRE007"].geometry
                                        }
                                        material={materials.ISS_03_dull}
                                        position={[1.087, 0.013, 0.061]}
                                      >
                                        <mesh
                                          geometry={
                                            nodes["29_DEXTRE008"].geometry
                                          }
                                          material={materials.ISS_03_dull}
                                          position={[1.087, -0.013, -0.327]}
                                        >
                                          <mesh
                                            geometry={
                                              nodes["29_DEXTRE009"].geometry
                                            }
                                            material={materials.ISS_03_dull}
                                            position={[0.282, -0.12, -0.112]}
                                          />
                                        </mesh>
                                      </mesh>
                                    </mesh>
                                  </mesh>
                                </mesh>
                                <mesh
                                  geometry={nodes["29_DEXTRE010"].geometry}
                                  material={materials.ISS_03_dull}
                                  position={[-1.38, 1.425, 0]}
                                >
                                  <mesh
                                    geometry={nodes["29_DEXTRE011"].geometry}
                                    material={materials.ISS_03_dull}
                                    position={[-0.375, -0.103, 0.269]}
                                  >
                                    <mesh
                                      geometry={nodes["29_DEXTRE012"].geometry}
                                      material={materials.ISS_03_dull}
                                      position={[-0.304, -0.113, 0.143]}
                                    >
                                      <mesh
                                        geometry={
                                          nodes["29_DEXTRE013"].geometry
                                        }
                                        material={materials.ISS_03_dull}
                                        position={[-1.087, 0.013, 0.061]}
                                      >
                                        <mesh
                                          geometry={
                                            nodes["29_DEXTRE014"].geometry
                                          }
                                          material={materials.ISS_03_dull}
                                          position={[-1.087, -0.013, -0.327]}
                                        >
                                          <mesh
                                            geometry={
                                              nodes["29_DEXTRE015"].geometry
                                            }
                                            material={materials.ISS_03_dull}
                                            position={[-0.282, -0.12, -0.112]}
                                          />
                                        </mesh>
                                      </mesh>
                                    </mesh>
                                  </mesh>
                                </mesh>
                              </mesh>
                            </group>
                          </mesh>
                        </mesh>
                      </mesh>
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
          </group>
          <group position={[-13.808, 0, 2.437]}>
            <mesh
              geometry={nodes.s0_ani000_5.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.s0_ani000_6.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.s0_ani000_7.geometry}
              material={materials["ISS_02_dark *"]}
            />
            <mesh
              geometry={nodes.s0_ani000_8.geometry}
              material={materials.ISS_AO_05}
            />
            <mesh
              geometry={nodes.s0_ani000_9.geometry}
              material={materials.ISS_04_dull}
            />
            <group position={[-1.441, -0.008, -0.94]}>
              <mesh
                geometry={nodes.s0_ani000_15.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_16.geometry}
                material={materials.ISS_AO_05}
              />
              <mesh
                geometry={nodes.s0_ani000_17.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_18.geometry}
                material={materials.ISS_02_dull}
              />
            </group>
            <group position={[-10.048, 0.005, -0.822]}>
              <mesh
                geometry={nodes.s0_ani000_19.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_20.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_21.geometry}
                material={materials.ISS_AO_05}
              />
              <group
                position={[-3.023, -0.027, -0.013]}
                rotation={[Math.PI / 3, 0, 0]}
              >
                <mesh
                  geometry={nodes.p6_ani000.geometry}
                  material={materials.ISS_AO_05}
                />
                <mesh
                  geometry={nodes.p6_ani000_1.geometry}
                  material={materials.ISS_02_dull}
                />
                <mesh
                  geometry={nodes.p6_ani000_2.geometry}
                  material={materials.ISS_AO_03}
                />
                <mesh
                  geometry={nodes.p6_ani000_3.geometry}
                  material={materials["ISS_02_dark *"]}
                />
                <mesh
                  geometry={nodes.p6_ani000_4.geometry}
                  material={materials.ISS_01_dull}
                />
                <group position={[-8.139, -0.009, 1.234]}>
                  <mesh
                    geometry={nodes.Cube008_46.geometry}
                    material={materials.ISS_01_dull}
                  />
                  <mesh
                    geometry={nodes.Cube008_47.geometry}
                    material={materials.ISS_AO_06}
                  />
                  <mesh
                    geometry={nodes.Cube008_48.geometry}
                    material={materials.ISS_02_dull}
                  />
                  <mesh
                    geometry={nodes.Cube008_49.geometry}
                    material={materials["ISS_02_dark *"]}
                  />
                  <group position={[0.487, 0.685, 0.665]}>
                    <mesh
                      geometry={nodes.p6_ani000_10.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_11.geometry}
                      material={materials.shiny_panel}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_12.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                  </group>
                  <group position={[0.487, -0.681, -2.391]}>
                    <mesh
                      geometry={nodes.p6_ani000_13.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_14.geometry}
                      material={materials.shiny_panel}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_15.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                  </group>
                  <group position={[-1.445, 0, -0.849]}>
                    <mesh
                      geometry={nodes.p6_ani000_16.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_17.geometry}
                      material={materials.ISS_AO_03}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_18.geometry}
                      material={materials.ISS_01_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_19.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                    <group position={[-13.492, 0.683, 1.522]}>
                      <mesh
                        geometry={nodes.p6_ani000_30.geometry}
                        material={materials.ISS_02_dull}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_31.geometry}
                        material={materials.shiny_panel}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_32.geometry}
                        material={materials["ISS_02_dark *"]}
                      />
                    </group>
                    <group position={[-13.492, -0.682, -1.534]}>
                      <mesh
                        geometry={nodes.p6_ani000_33.geometry}
                        material={materials.ISS_02_dull}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_34.geometry}
                        material={materials.shiny_panel}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_35.geometry}
                        material={materials["ISS_02_dark *"]}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group position={[-1.313, -2.246, -0.003]}>
                <mesh
                  geometry={nodes.ESP3000.geometry}
                  material={materials.ISS_01_dull}
                />
                <mesh
                  geometry={nodes.ESP3000_1.geometry}
                  material={materials.ISS_01_shiny_n}
                />
                <mesh
                  geometry={nodes.ESP3000_2.geometry}
                  material={materials.ISS_AO_07}
                />
                <mesh
                  geometry={nodes.ESP3000_3.geometry}
                  material={materials.ISS_03_dull}
                />
                <mesh
                  geometry={nodes.ESP3000_4.geometry}
                  material={materials.ISS_04_dull}
                />
              </group>
              <group position={[-1.845, 5.057, -0.003]}>
                <mesh
                  geometry={nodes.esp2_lo000_4.geometry}
                  material={materials.ISS_AO_07}
                />
                <mesh
                  geometry={nodes.esp2_lo000_5.geometry}
                  material={materials.ISS_04_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_6.geometry}
                  material={materials.ISS_01_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_7.geometry}
                  material={materials.ISS_03_dull}
                />
              </group>
              <group position={[2.208, -5.074, -0.003]}>
                <mesh
                  geometry={nodes.esp2_lo000_8.geometry}
                  material={materials.ISS_04_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_9.geometry}
                  material={materials.ISS_01_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_10.geometry}
                  material={materials.ISS_AO_07}
                />
              </group>
              <group position={[2.109, 3.717, -0.236]}>
                <mesh
                  geometry={nodes.AMS2000.geometry}
                  material={materials.ISS_04_dull}
                />
                <mesh
                  geometry={nodes.AMS2000_1.geometry}
                  material={materials.ISS_AO_07}
                />
                <mesh
                  geometry={nodes.AMS2000_2.geometry}
                  material={materials.ISS_01_dull}
                />
              </group>
            </group>
            <group position={[2.681, 1.908, 0.125]}>
              <mesh
                geometry={nodes.Cylinder022_63.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Cylinder022_64.geometry}
                material={materials.ISS_AO_07}
              />
              <mesh
                geometry={nodes.Cylinder022_65.geometry}
                material={materials.ISS_01_dull}
              />
            </group>
          </group>
          <group position={[6.822, 2.237, 1.504]}>
            <mesh
              geometry={nodes.s0_ani000_10.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.s0_ani000_11.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.s0_ani000_12.geometry}
              material={materials["ISS_02_dark *"]}
            />
            <mesh
              geometry={nodes.s0_ani000_13.geometry}
              material={materials.ISS_AO_05}
            />
            <mesh
              geometry={nodes.s0_ani000_14.geometry}
              material={materials.ISS_04_dull}
            />
            <group position={[8.427, -2.231, -0.007]}>
              <mesh
                geometry={nodes.s0_ani000_22.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_23.geometry}
                material={materials.ISS_AO_05}
              />
              <mesh
                geometry={nodes.s0_ani000_24.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_25.geometry}
                material={materials.ISS_02_dull}
              />
            </group>
            <group position={[17.042, -2.232, 0.111]}>
              <mesh
                geometry={nodes.s0_ani000_26.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_27.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.s0_ani000_28.geometry}
                material={materials.ISS_AO_05}
              />
              <group
                position={[3.016, 0.01, -0.034]}
                rotation={[Math.PI / 3, 0, 0]}
              >
                <mesh
                  geometry={nodes.p6_ani000_5.geometry}
                  material={materials.ISS_AO_05}
                />
                <mesh
                  geometry={nodes.p6_ani000_6.geometry}
                  material={materials.ISS_02_dull}
                />
                <mesh
                  geometry={nodes.p6_ani000_7.geometry}
                  material={materials.ISS_AO_03}
                />
                <mesh
                  geometry={nodes.p6_ani000_8.geometry}
                  material={materials["ISS_02_dark *"]}
                />
                <mesh
                  geometry={nodes.p6_ani000_9.geometry}
                  material={materials.ISS_01_dull}
                />
                <group position={[8.139, -0.009, -1.234]}>
                  <mesh
                    geometry={nodes.Cube008_50.geometry}
                    material={materials.ISS_01_dull}
                  />
                  <mesh
                    geometry={nodes.Cube008_51.geometry}
                    material={materials.ISS_AO_06}
                  />
                  <mesh
                    geometry={nodes.Cube008_52.geometry}
                    material={materials.ISS_02_dull}
                  />
                  <mesh
                    geometry={nodes.Cube008_53.geometry}
                    material={materials["ISS_02_dark *"]}
                  />
                  <group position={[1.445, 0, 0.849]}>
                    <mesh
                      geometry={nodes.p6_ani000_20.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_21.geometry}
                      material={materials.ISS_AO_03}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_22.geometry}
                      material={materials.ISS_01_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_23.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                    <group position={[13.492, -0.682, 1.534]}>
                      <mesh
                        geometry={nodes.p6_ani000_36.geometry}
                        material={materials.ISS_02_dull}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_37.geometry}
                        material={materials.shiny_panel}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_38.geometry}
                        material={materials["ISS_02_dark *"]}
                      />
                    </group>
                    <group position={[13.492, 0.683, -1.522]}>
                      <mesh
                        geometry={nodes.p6_ani000_39.geometry}
                        material={materials.ISS_02_dull}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_40.geometry}
                        material={materials.shiny_panel}
                      />
                      <mesh
                        geometry={nodes.p6_ani000_41.geometry}
                        material={materials["ISS_02_dark *"]}
                      />
                    </group>
                  </group>
                  <group position={[-0.487, -0.681, 2.391]}>
                    <mesh
                      geometry={nodes.p6_ani000_24.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_25.geometry}
                      material={materials.shiny_panel}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_26.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                  </group>
                  <group position={[-0.487, 0.685, -0.665]}>
                    <mesh
                      geometry={nodes.p6_ani000_27.geometry}
                      material={materials.ISS_02_dull}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_28.geometry}
                      material={materials.shiny_panel}
                    />
                    <mesh
                      geometry={nodes.p6_ani000_29.geometry}
                      material={materials["ISS_02_dark *"]}
                    />
                  </group>
                </group>
              </group>
              <group position={[1.057, -5.074, -0.045]}>
                <mesh
                  geometry={nodes.esp2_lo000_11.geometry}
                  material={materials.ISS_AO_07}
                />
                <mesh
                  geometry={nodes.esp2_lo000_12.geometry}
                  material={materials.ISS_03_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_13.geometry}
                  material={materials.ISS_04_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_14.geometry}
                  material={materials.ISS_01_dull}
                />
              </group>
              <group position={[1.843, 5.057, -0.072]}>
                <mesh
                  geometry={nodes.esp2_lo000_15.geometry}
                  material={materials.ISS_AO_08}
                />
                <mesh
                  geometry={nodes.esp2_lo000_16.geometry}
                  material={materials.ISS_01_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_17.geometry}
                  material={materials.ISS_04_dull}
                />
                <mesh
                  geometry={nodes.esp2_lo000_18.geometry}
                  material={materials.ISS_03_dull}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 0, 9.164]}>
          <mesh
            geometry={nodes.Cylinder022_36.geometry}
            material={nodes.Cylinder022_36.material}
          />
          <mesh
            geometry={nodes.Cylinder022_37.geometry}
            material={materials.ISS_01_shiny_n}
          />
          <mesh
            geometry={nodes.Cylinder022_38.geometry}
            material={materials.ISS_AO_01}
          />
          <mesh
            geometry={nodes.Cylinder022_39.geometry}
            material={materials.ISS_01_dull}
          />
          <group position={[0, 0, 6.968]}>
            <mesh
              geometry={nodes.Cylinder022_46.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.Cylinder022_47.geometry}
              material={materials.ISS_AO_02}
            />
            <mesh
              geometry={nodes.Cylinder022_48.geometry}
              material={materials.ISS_AO_01}
            />
          </group>
          <group position={[-4.172, 0, 4.83]}>
            <mesh
              geometry={nodes.Cylinder022_49.geometry}
              material={nodes.Cylinder022_49.material}
            />
            <mesh
              geometry={nodes.Cylinder022_50.geometry}
              material={materials.ISS_02_dull}
            />
            <mesh
              geometry={nodes.Cylinder022_51.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.Cylinder022_52.geometry}
              material={materials.ISS_01_shiny_n}
            />
            <mesh
              geometry={nodes.Cylinder022_53.geometry}
              material={materials.ISS_AO_01}
            />
            <mesh
              geometry={nodes.Cylinder022_54.geometry}
              material={materials.ISS_AO_06}
            />
            <group position={[-5.901, -1.334, 0]}>
              <mesh
                geometry={nodes.Cube008_35.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.Cube008_36.geometry}
                material={materials.ISS_AO_07}
              />
              <mesh
                geometry={nodes.Cube008_37.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Cube008_38.geometry}
                material={materials.foil_silver}
              />
              <mesh
                geometry={nodes.RapidScat_dish.geometry}
                material={materials.ISS_04_dull}
                position={[-0.731, -0.826, -0.219]}
              />
            </group>
          </group>
          <group position={[7.481, 0, 4.83]}>
            <mesh
              geometry={nodes.Cylinder022_55.geometry}
              material={nodes.Cylinder022_55.material}
            />
            <mesh
              geometry={nodes.Cylinder022_56.geometry}
              material={materials.ISS_03_dull}
            />
            <mesh
              geometry={nodes.Cylinder022_57.geometry}
              material={materials.ISS_01_dull}
            />
            <mesh
              geometry={nodes.Cylinder022_58.geometry}
              material={materials.ISS_AO_01}
            />
            <mesh
              geometry={nodes.Cylinder022_59.geometry}
              material={materials.ISS_03_shiny_n}
            />
            <mesh
              geometry={nodes.Cylinder022_60.geometry}
              material={materials.ISS_AO_04}
            />
            <group position={[2.822, 4.037, -0.002]}>
              <mesh
                geometry={nodes.Cylinder022_66.geometry}
                material={nodes.Cylinder022_66.material}
              />
              <mesh
                geometry={nodes.Cylinder022_67.geometry}
                material={materials.ISS_01_dull}
              />
              <mesh
                geometry={nodes.Cylinder022_68.geometry}
                material={materials.ISS_03_shiny_n}
              />
              <mesh
                geometry={nodes.Cylinder022_69.geometry}
                material={materials.ISS_AO_01}
              />
              <mesh
                geometry={nodes.Cylinder022_70.geometry}
                material={materials.ISS_AO_04}
              />
              <mesh
                geometry={nodes.Cylinder022_71.geometry}
                material={materials.ISS_03_dull}
              />
            </group>
            <mesh
              geometry={nodes["31_Robotic_Arm"].geometry}
              material={materials.ISS_04_dull}
              position={[5.138, 0.876, 1.681]}
            >
              <mesh
                geometry={nodes["31_Robotic_Arm001"].geometry}
                material={materials.ISS_04_dull}
                position={[0.757, 0.296, -0.327]}
              >
                <mesh
                  geometry={nodes["31_Robotic_Arm002"].geometry}
                  material={materials.ISS_04_dull}
                  position={[0, 0.408, 0.529]}
                >
                  <mesh
                    geometry={nodes["31_Robotic_Arm003"].geometry}
                    material={materials.ISS_04_dull}
                    position={[4.066, 0, -0.537]}
                  >
                    <mesh
                      geometry={nodes["31_Robotic_Arm004"].geometry}
                      material={materials.ISS_04_dull}
                      position={[4.074, 0, -0.52]}
                    >
                      <mesh
                        geometry={nodes["31_Robotic_Arm005"].geometry}
                        material={materials.ISS_04_dull}
                        position={[0.443, 0.515, 0.012]}
                      />
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <group position={[6.054, -1.561, -0.088]}>
              <mesh
                geometry={nodes.Cube008_39.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Cube008_40.geometry}
                material={materials.ISS_04_dull}
              />
              <mesh
                geometry={nodes.Cube008_41.geometry}
                material={materials.ISS_AO_07}
              />
              <mesh
                geometry={nodes.Cube008_42.geometry}
                material={materials.ISS_01_dull}
              />
            </group>
            <group position={[10.493, -1.946, -1.077]}>
              <mesh
                geometry={nodes.Cube008_43.geometry}
                material={materials.ISS_03_dull}
              />
              <mesh
                geometry={nodes.Cube008_44.geometry}
                material={materials.ISS_01_dull}
              />
            </group>
          </group>
        </group>
        <mesh
          geometry={nodes.Destiny_Window_Cover.geometry}
          material={materials.ISS_01_dull}
          position={[0, -2.323, 4.781]}
        />
      </group>
      <group position={[-3.695, -0.367, 0]}>
        <mesh
          geometry={nodes.Cylinder022_20.geometry}
          material={nodes.Cylinder022_20.material}
        />
        <mesh
          geometry={nodes.Cylinder022_21.geometry}
          material={materials.ISS_03_dull}
        />
        <mesh
          geometry={nodes.Cylinder022_22.geometry}
          material={materials.ISS_AO_04}
        />
        <mesh
          geometry={nodes.Cylinder022_23.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.Cylinder022_24.geometry}
          material={materials.ISS_03_shiny_n}
        />
        <mesh
          geometry={nodes.Cylinder022_25.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          geometry={nodes.Cylinder022_26.geometry}
          material={materials.ISS_AO_01}
        />
        <group position={[0.642, -0.004, 2.427]}>
          <mesh
            geometry={nodes.esp2_lo000.geometry}
            material={materials.ISS_04_dull}
          />
          <mesh
            geometry={nodes.esp2_lo000_1.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.esp2_lo000_2.geometry}
            material={materials.ISS_01_shiny_n}
          />
          <mesh
            geometry={nodes.esp2_lo000_3.geometry}
            material={materials.ISS_AO_07}
          />
        </group>
      </group>
      <group position={[2.234, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder022_27.geometry}
          material={nodes.Cylinder022_27.material}
        />
        <mesh
          geometry={nodes.Cylinder022_28.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          geometry={nodes.Cylinder022_29.geometry}
          material={materials.ISS_AO_01}
        />
        <mesh
          geometry={nodes.Cylinder022_30.geometry}
          material={materials.ISS_01_dull}
        />
        <group position={[6.968, 0, 0]}>
          <mesh
            geometry={nodes.Cylinder022_40.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.Cylinder022_41.geometry}
            material={materials.ISS_AO_02}
          />
          <mesh
            geometry={nodes.Cylinder022_42.geometry}
            material={materials.ISS_AO_01}
          />
        </group>
        <group position={[4.828, -2.622, 0]}>
          <mesh
            geometry={nodes.Cylinder022_43.geometry}
            material={materials.ISS_04_dull}
          />
          <mesh
            geometry={nodes.Cylinder022_44.geometry}
            material={materials.ISS_01_dull}
          />
          <mesh
            geometry={nodes.Cylinder022_45.geometry}
            material={materials.ISS_AO_01}
          />
          <mesh
            geometry={nodes["38_Cupola001"].geometry}
            material={materials.ISS_04_dull}
            position={[1.2, -0.358, -0.012]}
          />
          <mesh
            geometry={nodes["38_Cupola002"].geometry}
            material={materials.ISS_04_dull}
            position={[0.585, -0.358, 1.048]}
          />
          <mesh
            geometry={nodes["38_Cupola003"].geometry}
            material={materials.ISS_04_dull}
            position={[-0.575, -0.358, 1.054]}
          />
          <mesh
            geometry={nodes["38_Cupola004"].geometry}
            material={materials.ISS_04_dull}
            position={[-1.2, -0.358, 0]}
          />
          <mesh
            geometry={nodes["38_Cupola005"].geometry}
            material={materials.ISS_04_dull}
            position={[-0.585, -0.358, -1.048]}
          />
          <mesh
            geometry={nodes["38_Cupola006"].geometry}
            material={materials.ISS_04_dull}
            position={[0.615, -0.358, -1.031]}
          />
          <mesh
            geometry={nodes["38_Cupola007"].geometry}
            material={materials.ISS_04_dull}
            position={[-0.618, -1.049, 0.303]}
          />
          <mesh
            geometry={nodes.ISS.geometry}
            material={nodes.ISS.material}
            position={[0, -0.023, 0]}
          />
        </group>
      </group>
      <group position={[0, -2.191, 0]}>
        <mesh
          geometry={nodes.Cylinder022_31.geometry}
          material={nodes.Cylinder022_31.material}
        />
        <mesh
          geometry={nodes.Cylinder022_32.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          geometry={nodes.Cylinder022_33.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          geometry={nodes.Cylinder022_34.geometry}
          material={materials.ISS_AO_01}
        />
        <mesh
          geometry={nodes.Cylinder022_35.geometry}
          material={materials.ISS_AO_06}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ISS_stationary.glb");
